services:
  - type: web
    name: lugn-trygg-backend
    runtime: python
    pythonVersion: 3.11
    plan: free

    repo: https://github.com/omar1u7777/Lugn-Trygg
    branch: master

    rootDir: Backend

    buildCommand: pip install -r requirements.txt
    startCommand: python -m waitress --host=0.0.0.0 --port=$PORT main:app

    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: PYTHONUNBUFFERED
        value: "True"
      - key: PORT
        sync: false
      - key: WAITRESS_THREADS
        value: "2"
