name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET_KEY: test
      JWT_REFRESH_SECRET_KEY: test
      FIREBASE_WEB_API_KEY: test
      FIREBASE_API_KEY: test
      FIREBASE_PROJECT_ID: test
      FIREBASE_STORAGE_BUCKET: test
      FIREBASE_CREDENTIALS: mock.json

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 mypy

    - name: Create dummy Firebase credentials file
      run: echo "{}" > mock.json

    - name: Run tests
      run: |
        pytest -q

    - name: Run flake8
      run: |
        flake8 .

    - name: Run mypy
      run: |
        mypy Backend/src
